#!/usr/bin/env python3

import argparse
import sys
from pathlib import Path

import yaml  # type: ignore

from cgpclient.client import CGPClient
from cgpclient.fhir import ClientConfig  # type: ignore
from cgpclient.utils import APIM_BASE_URL, setup_logger


def parse_args(args: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Upload a genomic file associated with an NGIS referral "
            "and participant ID using the GDAM API in the NHS APIM"
        )
    )
    parser.add_argument(
        "-f",
        "--file",
        type=Path,
        help="File to upload",
        required=True,
    )
    parser.add_argument(
        "-i",
        "--index_file",
        type=Path,
        help="Index file to include in upload",
    )
    parser.add_argument(
        "-r",
        "--referral_id",
        type=str,
        help="NGIS referral ID, e.g r30000000001",
    )
    parser.add_argument(
        "-p",
        "--participant_id",
        type=str,
        help="NGIS participant ID, e.g p12345678303",
    )
    parser.add_argument(
        "-o",
        "--ods_code",
        type=str,
        help="ODS code for your organisation",
    )
    parser.add_argument("-s", "--sample_id", type=str, help="Sample identifier")
    parser.add_argument(
        "-id",
        "--run_id",
        type=str,
        help=(
            "Unique identifier for the sequencing run that generated the FASTQs, "
            "for a DRAGEN run this should be the run folder name"
        ),
    )
    parser.add_argument(
        "-t",
        "--tumour_id",
        type=str,
        help="Histopathology or SIHMDS identifier for a tumour sample",
    )
    parser.add_argument(
        "-host",
        "--api_host",
        type=str,
        help=f"API host base URL (default {APIM_BASE_URL})",
        default=APIM_BASE_URL,
    )
    parser.add_argument(
        "-api",
        "--api_name",
        type=str,
        help="API name (e.g. genomic-data-access)",
    )
    parser.add_argument(
        "-over",
        "--override_api_base_url",
        type=bool,
        help="Override the default API base URLs in all relevant URLs",
        default=False,
    )
    parser.add_argument(
        "-k",
        "--api_key",
        type=str,
        help=(
            "NHS APIM API key from application registered in "
            "https://digital.nhs.uk/developer"
        ),
    )
    parser.add_argument(
        "-pem",
        "--private_key_pem_file",
        type=Path,
        help=(
            "Path to private key PEM file, the corresponding public key "
            "must have been shared with NHS APIM"
        ),
    )
    parser.add_argument(
        "-kid",
        "--apim_kid",
        type=str,
        help=(
            "NHS APIM Keypair Identifier (KID), must have been shared "
            "with NHS APIM (default 'test-1')"
        ),
        default="test-1",
    )
    parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        help="Print verbose output",
    )
    parser.add_argument(
        "-vv",
        "--debug",
        action="store_true",
        help="Print debugging output",
    )
    parser.add_argument(
        "-cfg",
        "--config_file",
        type=Path,
        help="Configuration YAML file (default ~/.cgpclient/config.yaml)",
        default=Path.home() / ".cgpclient/config.yaml",
    )
    parser.add_argument(
        "-dr",
        "--dry_run",
        action="store_true",
        help="Just create the DRS and FHIR resources, don't actually upload anything",
    )
    parser.add_argument(
        "-w",
        "--workspace_id",
        type=str,
        help="FHIR server workspace ID",
    )

    parsed: argparse.Namespace = parser.parse_args(args)

    if parsed.config_file and parsed.config_file.is_file():
        # if we're passed a config file use it as default values
        # and then reparse
        config: dict = yaml.safe_load(parsed.config_file.read_text(encoding="utf-8"))
        parser.set_defaults(**config)
        parsed = parser.parse_args(args)

    return parsed


def main(cmdline_args: list[str]) -> None:
    args: argparse.Namespace = parse_args(cmdline_args)

    setup_logger(verbose=args.verbose, debug=args.debug)

    config: ClientConfig = ClientConfig(
        ods_code=args.ods_code,
        referral_id=args.referral_id,
        participant_id=args.participant_id,
        run_id=args.run_id,
        sample_id=args.sample_id,
        tumour_id=args.tumour_id,
        workspace_id=args.workspace_id,
    )

    client: CGPClient = CGPClient(
        api_host=args.api_host,
        api_name=args.api_name,
        api_key=args.api_key,
        private_key_pem=args.private_key_pem_file,
        apim_kid=args.apim_kid,
        override_api_base_url=args.override_api_base_url,
        dry_run=args.dry_run,
        config=config,
    )

    files: list[Path] = [args.file]

    if args.index_file is not None:
        files.append(args.index_file)

    client.upload_files(filenames=files)


if __name__ == "__main__":
    main(sys.argv[1:])
